{
 "title": "Goals",
 "time": { "from": "2020-01-07T17:55:40.000Z", "to": "2020-02-10T12:43:12.000Z" },
 "panels": [
  { "title": "Personal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stories Open",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM goals WHERE statusstorie = false"
    }
   ]
  },
  {
   "title": "Stories Complete",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM goals WHERE statusstorie = True"
    }
   ]
  },
  {
   "title": " Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    avg((category = 'objetivo' and statusstorie = false)::int) metrics\nfrom goals "
    }
   ]
  },
  {
   "title": " Backlog",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    avg((category not in ('objetivos') and statusstorie = false )::int) \"Backlog\"\nfrom goals "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "content": "<p style='color:grey'></p>\n<center>\n<h2>\n<b>\n<p style='color:grey'>\n\nDemand\n\n</p>\n</h2>\n</b>\n</center>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n    now() as Time,\n    category,\n    count(category) filter(where statusstorie = false)  stories\nfrom goals \ngroup by category\norder by stories desc"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(*) filter(where statusTwentyFive in ('true')) as \"Started\",\n    count(*) filter(where statusTwentyFive in ('false')) as \"Not Started\"\nfrom goals "
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(*) filter(where statusstorie = false and category not in ('objetivos'))  \"No Prioritized\",\n    count(*) filter(where statusstorie = false and category in ('objetivos')) \"Prioritized\"\nfrom goals "
    }
   ]
  },
  {
   "title": "Evolution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT startstorie as Time, category, count(*) FROM goals_history group by category, Time"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 9 },
   "content": "<p style='color:grey'></p>\n<center>\n<h2>\n<b>\n<p style='color:grey'>\n\nProgress\n\n</p>\n</h2>\n</b>\n</center>",
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select\n    now() as Time,\n    count(*) filter(where statusstorie = false and statusTwentyFive in ('true'))  \"25%\",\n    count(*) filter(where statusstorie = false and statusFifty in ('true')) \"50%\",\n    count(*) filter(where statusstorie = false and statusSeventyFive in ('true')) \"75%\",\n    count(*) filter(where statusstorie = false and statusOneHundred in ('true')) \"100%\"\nfrom goals "
    }
   ]
  },
  {
   "title": "Corporate",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  }
 ]
}